-- Generated by veaf-tools — do not edit.
-- Hands the mission's CTLD configuration to CTLD 2 and defers its start-up
-- to the VEAF framework (see docs/adr/0016-ctld2-sidecar-configuration.md).
ctld = ctld or {}
ctld.dontInitialize = true
ctld.configUser = [[
# GENERATED by ctld-tools (extract) — the source of truth for CTLD engine defaults.
# Sections mm_facing / advanced are for readability; the generator merges them.
# configVersion: the schema/catalogue version this document is authored against. A
# configUser carries it too, so the tool can detect a version gap on a CTLD upgrade.
configVersion: "2.0.0"
mm_facing:
  AASystemCrateStacking: false
  AASystemLimitBLUE: 20
  AASystemLimitRED: 20
  JTAC_LIMIT_BLUE: 10
  JTAC_LIMIT_RED: 10
  JTAC_allow9Line: true
  JTAC_allowSmokeRequest: true
  JTAC_allowStandbyMode: true
  JTAC_dropEnabled: true
  JTAC_jtacStatusF10: true
  JTAC_location: true
  JTAC_lock: all
  JTAC_maxDistance: 10000
  JTAC_targetDeconfliction: true
  aaAssemblyDistance: 500
  aaRearmDistance: 300
  addPlayerAircraftByType: true
  aiZones: []
  allowRandomAiTeamPickups: false
  capabilitiesByType:
    C-130J-30:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 22
      maxVehicleWeight: 20000
      loadableVehiclesBLUE:
      - M1045 HMMWV TOW
      - M1043 HMMWV Armament
      - Hummer
      loadableVehiclesRED:
      - BRDM-2
      - BTR_D
      maxWholeVehiclesOnboard: 2
      canParachuteDrop: true
      maxTroopsOnboard: 80
      useNativeDcsCargoSystem: true
      canTransportWholeVehicle: true
    Mi-8MT:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: true
      maxCratesOnboard: 2
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 16
      useNativeDcsCargoSystem: true
      canTransportWholeVehicle: true
    UH-1H:
      convertNativeLoadToCTLD: true
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: true
      maxCratesOnboard: 1
      maxVehicleWeight: 1360
      loadableVehiclesBLUE:
      - M1045 HMMWV TOW
      - M1043 HMMWV Armament
      - Hummer
      loadableVehiclesRED:
      - BRDM-2
      - BTR_D
      maxWholeVehiclesOnboard: 1
      canParachuteDrop: true
      maxTroopsOnboard: 8
      useNativeDcsCargoSystem: true
      canTransportWholeVehicle: true
    76MD:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 20
      maxVehicleWeight: 20000
      loadableVehiclesBLUE:
      - M1045 HMMWV TOW
      - M1043 HMMWV Armament
      - Hummer
      loadableVehiclesRED:
      - BRDM-2
      - BTR_D
      maxWholeVehiclesOnboard: 2
      canParachuteDrop: false
      maxTroopsOnboard: 80
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: true
    SK-60:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 1
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 4
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
    Mi-24P:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 1
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 10
      useNativeDcsCargoSystem: true
      canTransportWholeVehicle: false
    UH-60L:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: true
      maxCratesOnboard: 1
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 12
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
    CH-47Fbl1:
      convertNativeLoadToCTLD: true
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: true
      maxCratesOnboard: 8
      maxVehicleWeight: 11000
      loadableVehiclesBLUE:
      - M1045 HMMWV TOW
      - M1043 HMMWV Armament
      - Hummer
      loadableVehiclesRED:
      - BRDM-2
      - BTR_D
      maxWholeVehiclesOnboard: 1
      canParachuteDrop: true
      maxTroopsOnboard: 40
      useNativeDcsCargoSystem: true
      canTransportWholeVehicle: false
    Hercules:
      convertNativeLoadToCTLD: false
      cratesEnabled: true
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 1
      maxVehicleWeight: 20000
      loadableVehiclesBLUE:
      - M1045 HMMWV TOW
      - M1043 HMMWV Armament
      - Hummer
      loadableVehiclesRED:
      - BRDM-2
      - BTR_D
      maxWholeVehiclesOnboard: 2
      canParachuteDrop: false
      maxTroopsOnboard: 30
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: true
    SA342L:
      convertNativeLoadToCTLD: false
      cratesEnabled: false
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 0
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 1
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
    SA342M:
      convertNativeLoadToCTLD: false
      cratesEnabled: false
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 0
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 1
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
    SA342Minigun:
      convertNativeLoadToCTLD: false
      cratesEnabled: false
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 0
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 1
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
    SA342Mistral:
      convertNativeLoadToCTLD: false
      cratesEnabled: false
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 0
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 1
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
    Yak-52:
      convertNativeLoadToCTLD: false
      cratesEnabled: false
      troopsEnabled: true
      canSlingload: false
      maxCratesOnboard: 0
      maxWholeVehiclesOnboard: 0
      canParachuteDrop: false
      maxTroopsOnboard: 1
      useNativeDcsCargoSystem: false
      canTransportWholeVehicle: false
  disableAllSmoke: false
  dynamicZoneRadius: 200
  enableAllCrates: true
  enableCrates: true
  enableFARPRepack: true
  enableFastRopeInsertion: true
  enableHoverSlingload: true
  enablePackingVehicles: true
  enableSmokeDrop: true
  enabledFOBBuilding: true
  enabledRadioBeaconDrop: true
  extractableGroups: []
  farpTroopPickupRadius: 150
  fastRopeMaximumHeight: 18.28
  fobCrateCollectionRadius: 750
  fobDestructionThreshold: 0.5
  fobLogisticZoneRadius: 150
  fobMinDistanceFromZones: 500
  fobTroopPickupRadius: 150
  groundVehicleWeights:
    BTR_D: 8000
    Hummer: 2400
    BRDM-2: 7000
    M1045 HMMWV TOW: 5000
    M1043 HMMWV Armament: 2500
  loadCrateFromMenu: true
  loadCrateSearchRadius: 50
  loadableGroups:
  - name: Standard Group
    at: 2
    mg: 2
    inf: 6
  - name: Anti Air
    aa: 3
    inf: 2
  - name: Anti Tank
    at: 6
    inf: 2
  - name: Mortar Squad
    mortar: 6
  - name: JTAC Group
    jtac: 1
    inf: 4
  - name: JTAC Group 2
    jtac: 2
    inf: 4
  - name: Single JTAC
    jtac: 1
  - name: 2x - Standard Groups
    at: 4
    mg: 4
    inf: 12
  - name: 2x - Anti Air
    aa: 6
    inf: 4
  - name: 2x - Anti Tank
    at: 12
    inf: 4
  - name: 2x - Standard Groups + 2x Mortar
    at: 4
    mg: 4
    mortar: 12
    inf: 12
  - name: 3x - Standard Groups
    at: 6
    mg: 6
    inf: 18
  - name: 3x - Anti Air
    aa: 9
    inf: 6
  - name: 3x - Anti Tank
    at: 18
    inf: 6
  - name: 3x - Mortar Squad
    mortar: 18
  - name: 5x - Mortar Squad
    mortar: 30
  location_DMS: false
  logisticUnits: []
  logisticUnitTypes:
  - LHA_Tarawa
  - Stennis
  - CVN_71
  - KUZNECOW
  - FARP Ammo Dump Coating
  maxExtractDistance: 125
  maxSlingloadSpeed: 26
  maxTransportWeight: 0
  maximumDistanceLogistic: 200
  maximumDistancePackableUnitsSearch: 200
  maximumSearchDistance: 3000
  nbLimitSpawnedTroops:
  - 0
  - 0
  numberOfTroops: 10
  reconEnabled: false
  reconF10Menu: true
  reconIconScale: 1.0
  reconMinAltitude: 50
  reconRefreshInterval: 10
  reconSearchRadius: 5000
  showMinefieldOnF10Map: true
  slingCutDestroyHeight: 40
  slingLoad: false
  unpackSearchRadius: 300
  spawnableCrates:
    Combat Vehicles:
    - unit: M1043 HMMWV Armament
      desc: Humvee - MG
      weight: 1000.01
      cratesRequired: 3
      side: 2
    - unit: M1045 HMMWV TOW
      desc: Humvee - TOW
      weight: 1000.02
      cratesRequired: 5
      side: 2
    - unit: MaxxPro_MRAP
      desc: Light Tank - MRAP
      weight: 1000.03
      cratesRequired: 2
      side: 2
    - unit: LAV-25
      desc: Med Tank - LAV-25
      weight: 1000.04
      cratesRequired: 3
      side: 2
    - unit: M-1 Abrams
      desc: Heavy Tank - Abrams
      weight: 1000.05
      cratesRequired: 4
      side: 2
    - unit: BTR_D
      desc: BTR-D
      weight: 1000.11
      cratesRequired: 8
      side: 1
    - unit: BRDM-2
      desc: BRDM-2
      weight: 1000.12
      cratesRequired: 7
      side: 1
    Artillery:
    - unit: MLRS
      desc: MLRS
      weight: 1002.01
      cratesRequired: 3
      side: 2
    - unit: SpGH_Dana
      desc: SpGH DANA
      weight: 1002.02
      cratesRequired: 3
      side: 2
    - unit: T155_Firtina
      desc: T155 Firtina
      weight: 1002.03
      cratesRequired: 3
      side: 2
    - unit: M-109
      desc: Howitzer
      weight: 1002.04
      cratesRequired: 3
      side: 2
    - unit: SAU Msta
      desc: SPH 2S19 Msta
      weight: 1002.11
      cratesRequired: 3
      side: 1
    Support:
    - unit: Hummer
      desc: Hummer - JTAC
      weight: 1001.01
      isJTAC: true
      cratesRequired: 2
      side: 2
    - unit: M 818
      desc: M-818 Ammo Truck
      weight: 1001.02
      cratesRequired: 2
      side: 2
    - unit: M978 HEMTT Tanker
      desc: M-978 Tanker
      weight: 1001.03
      cratesRequired: 2
      side: 2
    - unit: SKP-11
      desc: SKP-11 - JTAC
      weight: 1001.11
      isJTAC: true
      side: 1
    - unit: Ural-375
      desc: Ural-375 Ammo Truck
      weight: 1001.12
      cratesRequired: 2
      side: 1
    - unit: KAMAZ Truck
      desc: KAMAZ Ammo Truck
      weight: 1001.13
      cratesRequired: 2
      side: 1
    - weight: 1001.21
      cratesRequired: 3
      unit: FPS-117
      desc: EWR Radar
    SAM short range:
    - unit: M1097 Avenger
      desc: M1097 Avenger
      weight: 1003.01
      cratesRequired: 3
      side: 2
    - unit: M48 Chaparral
      desc: M48 Chaparral
      weight: 1003.02
      cratesRequired: 2
      side: 2
    - unit: Roland ADS
      desc: Roland ADS
      weight: 1003.03
      cratesRequired: 3
      side: 2
    - unit: Gepard
      desc: Gepard AAA
      weight: 1003.04
      cratesRequired: 3
      side: 2
    - unit: HEMTT_C-RAM_Phalanx
      desc: LPWS C-RAM
      weight: 1003.05
      cratesRequired: 3
      side: 2
    - unit: Osa 9A33 ln
      desc: 9K33 Osa
      weight: 1003.11
      cratesRequired: 3
      side: 1
    - unit: Strela-1 9P31
      desc: 9P31 Strela-1
      weight: 1003.12
      cratesRequired: 3
      side: 1
    - unit: Strela-10M3
      desc: 9K35M Strela-10
      weight: 1003.13
      cratesRequired: 3
      side: 1
    - unit: Tor 9A331
      desc: 9K331 Tor
      weight: 1003.14
      cratesRequired: 3
      side: 1
    - unit: 2S6 Tunguska
      desc: 2K22 Tunguska
      weight: 1003.15
      cratesRequired: 3
      side: 1
    Drone:
    - spawnAs: AIRPLANE
      unit: MQ-9 Reaper
      desc: MQ-9 Repear - JTAC
      weight: 1006.01
      isJTAC: true
      side: 2
    - spawnAs: AIRPLANE
      unit: RQ-1A Predator
      desc: RQ-1A Predator - JTAC
      weight: 1006.11
      isJTAC: true
      side: 1
    SAM mid range:
    - unit: Hawk ln
      desc: HAWK Launcher
      weight: 1004.01
      cratesRequired: 1
      side: 2
    - unit: Hawk sr
      desc: HAWK Search Radar
      weight: 1004.02
      cratesRequired: 1
      side: 2
    - unit: Hawk tr
      desc: HAWK Track Radar
      weight: 1004.03
      cratesRequired: 1
      side: 2
    - unit: Hawk pcp
      desc: HAWK PCP
      weight: 1004.04
      cratesRequired: 1
      side: 2
    - unit: Hawk cwar
      desc: HAWK CWAR
      weight: 1004.05
      cratesRequired: 1
      side: 2
    - desc: HAWK - All crates
      side: 2
      mixedSet:
      - 1004.01
      - 1004.02
      - 1004.03
    - desc: HAWK Repair
      weight: 1004.06
      cratesRequired: 1
      side: 2
      _repairFor: HAWK AA System
    - unit: NASAMS_LN_C
      desc: NASAMS Launcher 120C
      weight: 1004.11
      cratesRequired: 1
      side: 2
    - unit: NASAMS_Radar_MPQ64F1
      desc: NASAMS Search/Track Radar
      weight: 1004.12
      cratesRequired: 1
      side: 2
    - unit: NASAMS_Command_Post
      desc: NASAMS Command Post
      weight: 1004.13
      cratesRequired: 1
      side: 2
    - desc: NASAMS - All crates
      side: 2
      mixedSet:
      - 1004.11
      - 1004.12
      - 1004.13
    - desc: NASAMS Repair
      weight: 1004.14
      cratesRequired: 1
      side: 2
      _repairFor: NASAMS AA System
    - unit: SA-11 Buk LN 9A310M1
      desc: BUK Launcher
      weight: 1004.31
      cratesRequired: 1
      side: 1
    - unit: SA-11 Buk SR 9S18M1
      desc: BUK Search Radar
      weight: 1004.32
      cratesRequired: 1
      side: 1
    - unit: SA-11 Buk CC 9S470M1
      desc: BUK CC Radar
      weight: 1004.33
      cratesRequired: 1
      side: 1
    - desc: BUK - All crates
      side: 1
      mixedSet:
      - 1004.31
      - 1004.32
      - 1004.33
    - desc: BUK Repair
      weight: 1004.34
      cratesRequired: 1
      side: 1
      _repairFor: BUK AA System
    - unit: Kub 2P25 ln
      desc: KUB Launcher
      weight: 1004.21
      cratesRequired: 1
      side: 1
    - unit: Kub 1S91 str
      desc: KUB Radar
      weight: 1004.22
      cratesRequired: 1
      side: 1
    - desc: KUB - All crates
      side: 1
      mixedSet:
      - 1004.21
      - 1004.22
    - desc: KUB Repair
      weight: 1004.23
      cratesRequired: 1
      side: 1
      _repairFor: KUB AA System
    SAM long range:
    - unit: Patriot ln
      desc: Patriot Launcher
      weight: 1005.01
      cratesRequired: 1
      side: 2
    - unit: Patriot str
      desc: Patriot Radar
      weight: 1005.02
      cratesRequired: 1
      side: 2
    - unit: Patriot ECS
      desc: Patriot ECS
      weight: 1005.03
      cratesRequired: 1
      side: 2
    - unit: Patriot AMG
      desc: Patriot AMG (optional)
      weight: 1005.06
      cratesRequired: 1
      side: 2
    - desc: Patriot - All crates
      side: 2
      mixedSet:
      - 1005.01
      - 1005.02
      - 1005.03
    - desc: Patriot Repair
      weight: 1005.07
      cratesRequired: 1
      side: 2
      _repairFor: Patriot AA System
    - unit: S-300PS 5P85C ln
      desc: S-300 Grumble TEL C
      weight: 1005.11
      cratesRequired: 1
      side: 1
    - unit: S-300PS 40B6M tr
      desc: S-300 Grumble Flap Lid-A TR
      weight: 1005.12
      cratesRequired: 1
      side: 1
    - unit: S-300PS 40B6MD sr
      desc: S-300 Grumble Clam Shell SR
      weight: 1005.13
      cratesRequired: 1
      side: 1
    - unit: S-300PS 64H6E sr
      desc: S-300 Grumble Big Bird SR
      weight: 1005.14
      cratesRequired: 1
      side: 1
    - unit: S-300PS 54K6 cp
      desc: S-300 Grumble C2
      weight: 1005.15
      cratesRequired: 1
      side: 1
    - desc: S-300 - All crates
      side: 1
      mixedSet:
      - 1005.11
      - 1005.12
      - 1005.13
      - 1005.14
      - 1005.15
    - desc: S-300 Repair
      weight: 1005.16
      cratesRequired: 1
      side: 1
      _repairFor: S-300 AA System
  transportPilotNames:
  - helicargo1
  - helicargo2
  - helicargo3
  - helicargo4
  - helicargo5
  - helicargo6
  - helicargo7
  - helicargo8
  - helicargo9
  - helicargo10
  - helicargo11
  - helicargo12
  - helicargo13
  - helicargo14
  - helicargo15
  - helicargo16
  - helicargo17
  - helicargo18
  - helicargo19
  - helicargo20
  - helicargo21
  - helicargo22
  - helicargo23
  - helicargo24
  - helicargo25
  - 'MEDEVAC #1'
  - 'MEDEVAC #2'
  - 'MEDEVAC #3'
  - 'MEDEVAC #4'
  - 'MEDEVAC #5'
  - 'MEDEVAC #6'
  - 'MEDEVAC #7'
  - 'MEDEVAC #8'
  - 'MEDEVAC #9'
  - 'MEDEVAC #10'
  - 'MEDEVAC #11'
  - 'MEDEVAC #12'
  - 'MEDEVAC #13'
  - 'MEDEVAC #14'
  - 'MEDEVAC #15'
  - 'MEDEVAC #16'
  - 'MEDEVAC RED #1'
  - 'MEDEVAC RED #2'
  - 'MEDEVAC RED #3'
  - 'MEDEVAC RED #4'
  - 'MEDEVAC RED #5'
  - 'MEDEVAC RED #6'
  - 'MEDEVAC RED #7'
  - 'MEDEVAC RED #8'
  - 'MEDEVAC RED #9'
  - 'MEDEVAC RED #10'
  - 'MEDEVAC RED #11'
  - 'MEDEVAC RED #12'
  - 'MEDEVAC RED #13'
  - 'MEDEVAC RED #14'
  - 'MEDEVAC RED #15'
  - 'MEDEVAC RED #16'
  - 'MEDEVAC RED #17'
  - 'MEDEVAC RED #18'
  - 'MEDEVAC RED #19'
  - 'MEDEVAC RED #20'
  - 'MEDEVAC RED #21'
  - 'MEDEVAC BLUE #1'
  - 'MEDEVAC BLUE #2'
  - 'MEDEVAC BLUE #3'
  - 'MEDEVAC BLUE #4'
  - 'MEDEVAC BLUE #5'
  - 'MEDEVAC BLUE #6'
  - 'MEDEVAC BLUE #7'
  - 'MEDEVAC BLUE #8'
  - 'MEDEVAC BLUE #9'
  - 'MEDEVAC BLUE #10'
  - 'MEDEVAC BLUE #11'
  - 'MEDEVAC BLUE #12'
  - 'MEDEVAC BLUE #13'
  - 'MEDEVAC BLUE #14'
  - 'MEDEVAC BLUE #15'
  - 'MEDEVAC BLUE #16'
  - 'MEDEVAC BLUE #17'
  - 'MEDEVAC BLUE #18'
  - 'MEDEVAC BLUE #19'
  - 'MEDEVAC BLUE #20'
  - 'MEDEVAC BLUE #21'
  - transport1
  - transport2
  - transport3
  - transport4
  - transport5
  - transport6
  - transport7
  - transport8
  - transport9
  - transport10
  - transport11
  - transport12
  - transport13
  - transport14
  - transport15
  - transport16
  - transport17
  - transport18
  - transport19
  - transport20
  - transport21
  - transport22
  - transport23
  - transport24
  - transport25
  troopPickupAtFARP: true
  troopPickupAtFOB: true
  troopZoneShipTypes:
  - LHA_Tarawa
  - Stennis
  - CVN_71
  - KUZNECOW
  troopZones:
  - - pickzone1
    - blue
    - -1
    - yes
    - 0
  - - pickzone2
    - red
    - -1
    - yes
    - 0
  - - pickzone3
    - none
    - -1
    - yes
    - 0
  - - pickzone4
    - none
    - -1
    - yes
    - 0
  - - pickzone5
    - none
    - -1
    - yes
    - 0
  - - pickzone6
    - none
    - -1
    - yes
    - 0
  - - pickzone7
    - none
    - -1
    - yes
    - 0
  - - pickzone8
    - none
    - -1
    - yes
    - 0
  - - pickzone9
    - none
    - 5
    - yes
    - 1
  - - pickzone10
    - none
    - 10
    - yes
    - 2
  - - pickzone11
    - blue
    - 20
    - no
    - 2
  - - pickzone12
    - red
    - 20
    - no
    - 1
  - - pickzone13
    - none
    - -1
    - yes
    - 0
  - - pickzone14
    - none
    - -1
    - yes
    - 0
  - - pickzone15
    - none
    - -1
    - yes
    - 0
  - - pickzone16
    - none
    - -1
    - yes
    - 0
  - - pickzone17
    - none
    - -1
    - yes
    - 0
  - - pickzone18
    - none
    - -1
    - yes
    - 0
  - - pickzone19
    - none
    - 5
    - yes
    - 0
  - - pickzone20
    - none
    - 10
    - yes
    - 0
    - 1000
  - - USA Carrier
    - blue
    - 10
    - yes
    - 0
    - 1001
  wpZones:
  - - wpzone1
    - green
    - yes
    - 2
  - - wpzone2
    - blue
    - yes
    - 2
  - - wpzone3
    - orange
    - yes
    - 2
  - - wpzone4
    - none
    - yes
    - 2
  - - wpzone5
    - none
    - yes
    - 2
  - - wpzone6
    - none
    - yes
    - 1
  - - wpzone7
    - none
    - yes
    - 1
  - - wpzone8
    - none
    - yes
    - 1
  - - wpzone9
    - none
    - yes
    - 1
  - - wpzone10
    - none
    - no
    - 0
advanced:
  CIV_WEIGHT: 2
  JTAC_WEIGHT: 15
  JTAC_droneAltitude: 3000
  jtacLaserCodeMax: 1688
  jtacLaserCodeMin: 1111
  JTAC_droneRadiusNoLase: 2000
  JTAC_droneRadiusOnLase: 1000
  JTAC_droneSpeed: 150
  JTAC_laseIntervalSeconds: 15
  JTAC_laseSpotCorrections: true
  JTAC_searchIntervalSeconds: 10
  JTAC_smokeColour_BLUE: 1
  JTAC_smokeColour_RED: 4
  JTAC_smokeMarginOfError: 50
  JTAC_smokeOffset_x: 0.0
  JTAC_smokeOffset_y: 2.0
  JTAC_smokeOffset_z: 0.0
  JTAC_smokeOn_BLUE: false
  JTAC_smokeOn_RED: false
  KIT_WEIGHT: 20
  MANPAD_WEIGHT: 18
  MG_WEIGHT: 10
  MORTAR_WEIGHT: 26
  RIFLE_WEIGHT: 5
  RPG_WEIGHT: 7.6
  SOLDIER_WEIGHT: 80
  aaLaunchers: 3
  autoUnpackRadiusParachute: 1000
  beaconAutoRefreshLayer: false
  beaconIconColor:
  - 1.0
  - 0.5
  - 0.0
  - 1.0
  beaconIconRadius: 25
  beaconLayerEnabled: false
  beaconRefreshInterval: 60
  beaconRemovalRadius: 500
  beaconTextSize: 12
  crateSpacing: 5
  ctldLogPath: ''
  debug: false
  debugScreenLog: false
  debugScreenLogDuration: 10
  defaultVehicleWeight: 2500
  defaultZoneRadius: 500
  fieldExtractTroopWeight: 130
  demineRadius: 150
  deployedBeaconBattery: 30
  enableAutoOrbitingFlyingJtacOnTarget: true
  groundAglThreshold: 5.0
  hoverTime: 10
  maxDistanceFromCrate: 5.5
  maximumHoverHeight: 12.0
  minimumHoverHeight: 7.5
  modTypes: []
  parachuteDescentRateCrates: 5
  parachuteDescentRateTroops: 5
  parachuteDescentRateVehicles: 8
  parachuteInertiaFactor: 0.3
  parachuteLateralDriftMax: 80
  parachuteLateralDriftMin: 10
  parachuteMinAltitudeCrates: 152
  parachuteMinAltitudeTroops: 152
  parachuteMinAltitudeVehicles: 152
  radioSound: beacon.ogg
  radioSoundFC3: beaconsilent.ogg
  smokeAutoResume: false
  smokeAutoResumeInterval: 270
  smokeRefreshInterval: 300
  spawnDistanceInCircle: 10
  spawnableCratesModels:
    load:
      canCargo: true
      type: ammo_cargo
    sling:
      canCargo: true
      shape_name: bw_container_cargo
      type: container_cargo
    dynamic:
      canCargo: true
      type: ammo_cargo
]]
